const CODE_MESSAGES = {
    SUCCESS: 0,
    ERROR_RECEIVER_NOT_EXIST: 101,
    ERROR_MESSAGE_NOT_EXIST: 102,
    ERROR_RECEIVER_WRONG: 103,
    ERROR_SENDER_WRONG: 104,
    ERROR_STATUS_NOT_EXIST: 105,
    ERROR_NOT_GROUP_MEMBER: 106,
    ERROR_GROUP_NOT_EXIST: 107,
    ERROR_CONTENT_LACK: 108,
    ERROR_OTHER: 100,
}

module.exports = {
    CODE_MESSAGES,
}
