const CODES_MESSAGES = {
    SUCCESS: 0,
    ERROR_RECEIVER_NOT_EXIST: 101,
    ERROR_MESSAGE_NOT_EXIST: 102,
    ERROR_RECEIVER_WRONG: 103,
    ERROR_SENDER_WRONG: 104,
    ERROR_STATUS_NOT_EXIST: 105,
    ERROR_NOT_GROUP_MEMBER: 106,
    ERROR_GROUP_NOT_EXIST: 107,
    ERROR_CONTENT_LACK: 108,
    ERROR_OTHER: 100,
}

const CODES_USERS = {
    SUCCESS: 0,
    ERROR_USER_NOT_EXIST: 101,
    ERROR_EMAIL_EXIST: 102,
    ERROR_PASSWORD_WRONG: 103,
    ERROR_OTHER: 100,
}

const CODES_CAPTCHAS = {
    SUCCESS: 0,
    ERROR_EMAIL_FORMAT_WRONG: 101,
    ERROR_CAPTCHA_EXPIRE_OR_NOT_EXIST_BEFORE: 102,
    ERROR_CAPTCHA_WRONG: 103,
    ERROR_OTHER: 100,
}

const CODES_POSTS = {
    SUCCESS: 0,
    ERROR_TYPE_WRONG: 101,
    ERROR_SUBJECT_WRONG: 102,
    ERROR_NOT_FRIENDS: 103,
    ERROR_POST_NOT_EXIST: 104,
    ERROR_USER_NOT_EXIST: 105,
    ERROR_COMMENT_NOT_EXIST: 106,
    ERROR_OTHER: 100,
}

const CODES_RELATIONS = {
    SUCCESS: 0,
    ERROR_FRIEND_NOT_EXIST: 101,
    ERROR_GROUP_NOT_EXIST: 102,
    ERROR_INVITATION_FAIL: 103,
    ERROR_TYPE_WRONG: 104,
    ERROR_OTHER: 100,
}

module.exports = {
    CODES_MESSAGES,
    CODES_USERS,
    CODES_CAPTCHAS,
    CODES_POSTS,
    CODES_RELATIONS,
}
